### ISSUE TITLE
I have an idea

### ISSUE THREAD

**Issue by nguyenson071202** [StageGuard/SkyAutoPlayerScript#6]
I think you should add the ability to hide the playback toolbar. Specifically, you can add 1 toolbar minimize button.Or I think you can add the option to hide the toolbar on the notification bar, and control it in the notification bar. In short, I think we'll need a minimize button.Thank you for reading my request !!
Here is an image for the example I have just given.![Screenshot_2021-04-06-23-56-57-25_e08b3c7e013d63887f51fcd172db7056.jpg](https://user-images.githubusercontent.com/75987452/113749544-f2f1ef00-9733-11eb-9233-ee0b66a2cf54.jpg)

**Comment by StageGuard** [comment]
Hidding all window while playing is dangerous. You know this script works with accessibility and emulate touching screen. If something unexpected happened(e.g. close piano roll or touch a floating notification accidently), you almost cannot deal with it because script is stilling touching screen. So I didn't add button to hide playing panel.
But anyway, if more people need this feature, I will consider adding it.

**Comment by nguyenson071202** [comment]
> Hidding all window while playing is dangerous. You know this script works with accessibility and emulate touching screen. If something unexpected happened(e.g. close piano roll or touch a floating notification accidently), you almost cannot deal with it because script is stilling touching screen. So I didn't add button to hide playing panel.
> But anyway, if more people need this feature, I will consider adding it.

If you add the toolbar hidden feature to the notification bar, you can set the pause button to buttons like volume up / down, or swiping down the notification bar will pause it. If not, you can make it look like a Messenger chat bubble. Thank you for the reply.

**Comment by StageGuard** [comment]
@nguyenson071202 I will try it.

**Comment by StageGuard** [comment]
I have released `Version 23` which supported it.
